#!/usr/bin/env python3
"""
AJ Studios AI API - Setup Script
Helps configure your environment variables securely
"""

import os
import shutil
from pathlib import Path

def setup_environment():
    """Setup environment variables for AJ Studios AI API"""
    
    print("🚀 AJ Studios AI API - Environment Setup")
    print("=" * 50)
    
    # Check if .env already exists
    if os.path.exists('.env'):
        print("✅ .env file already exists")
        response = input("Do you want to update it? (y/N): ").strip().lower()
        if response not in ['y', 'yes']:
            print("Setup cancelled.")
            return
        
        # Backup existing .env
        shutil.copy('.env', '.env.backup')
        print("📝 Backed up existing .env to .env.backup")
    
    # Get GitHub token
    print("\n🎓 GitHub Models API Setup (FREE for students)")
    print("Go to: https://github.com/settings/tokens/new")
    print("Permissions needed: repo, read:org, read:user")
    
    github_token = input("\nEnter your GitHub token: ").strip()
    
    if not github_token:
        print("❌ GitHub token is required!")
        return False
    
    # Validate token format
    if not github_token.startswith(('ghp_', 'github_pat_')):
        print("⚠️  Warning: Token doesn't look like a GitHub token")
        response = input("Continue anyway? (y/N): ").strip().lower()
        if response not in ['y', 'yes']:
            return False
    
    # Optional: Database URL
    print("\n📊 Database Setup (Optional)")
    print("Leave blank to skip database features")
    database_url = input("Enter Neon database URL (optional): ").strip()
    
    # Optional: Ollama URL
    print("\n🖥️  Local Ollama Setup (Optional)")
    print("Default: http://localhost:11434")
    ollama_url = input("Enter Ollama URL (or press Enter for default): ").strip()
    if not ollama_url:
        ollama_url = "http://localhost:11434"
    
    # Create .env file
    env_content = f"""# AJ Studios AI API - Environment Variables
# Generated by setup script

# === GITHUB MODELS API (FREE for students!) ===
GITHUB_TOKEN={github_token}

# === DATABASE (Optional) ===
{f'DATABASE_URL={database_url}' if database_url else '# DATABASE_URL=your_neon_database_url_here'}

# === LOCAL OLLAMA ===
OLLAMA_URL={ollama_url}

# === DEVELOPMENT ===
NODE_ENV=development

# === ADDITIONAL API KEYS (Optional) ===
# Add these if you want more AI providers:
# GROQ_API_KEY1=your_groq_key_here
# OPENROUTER_API_KEY1=your_openrouter_key_here
# CHUTES_API_TOKEN=your_chutes_token_here
# CEREBRAS_API_KEY=your_cerebras_key_here
"""
    
    with open('.env', 'w') as f:
        f.write(env_content)
    
    print("\n✅ Environment setup complete!")
    print("📁 Created .env file with your configuration")
    print("\n🚀 Next steps:")
    print("1. Install dependencies: npm install")
    print("2. Test GitHub API: python github_models_final.py")
    print("3. Start the server: npm run dev")
    print("\n🔒 Security: .env file is already in .gitignore")
    
    return True

def test_github_token():
    """Test if GitHub token works"""
    print("\n🧪 Testing GitHub Models API...")
    
    try:
        from dotenv import load_dotenv
        import requests
        
        load_dotenv()
        token = os.getenv("GITHUB_TOKEN")
        
        if not token:
            print("❌ No GITHUB_TOKEN found in environment")
            return False
        
        # Test API call
        headers = {
            "Authorization": f"Bearer {token}",
            "Content-Type": "application/json"
        }
        
        data = {
            "model": "gpt-4o-mini",
            "messages": [{"role": "user", "content": "Say 'Hello' if you can hear me"}],
            "max_tokens": 10
        }
        
        response = requests.post(
            "https://models.inference.ai.azure.com/chat/completions",
            headers=headers,
            json=data,
            timeout=30
        )
        
        if response.status_code == 200:
            result = response.json()
            message = result["choices"][0]["message"]["content"]
            print(f"✅ GitHub Models API working! Response: {message}")
            return True
        else:
            print(f"❌ API Error {response.status_code}: {response.text}")
            return False
            
    except ImportError:
        print("❌ Missing dependencies. Run: pip install requests python-dotenv")
        return False
    except Exception as e:
        print(f"❌ Test failed: {str(e)}")
        return False

if __name__ == "__main__":
    print("AJ Studios AI API Setup")
    print("======================")
    
    choice = input("\nChoose an option:\n1. Setup environment\n2. Test GitHub API\n3. Both\nChoice (1-3): ").strip()
    
    if choice in ['1', '3']:
        setup_success = setup_environment()
        if not setup_success:
            exit(1)
    
    if choice in ['2', '3']:
        test_github_token()
    
    print("\n🎉 Setup complete! Your AI API is ready to use.")